//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SvestapolEntities : DbContext
    {
        public SvestapolEntities()
            : base("name=SvestapolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pass_DeathCause> Pass_DeathCause { get; set; }
        public virtual DbSet<Pass_Origin> Pass_Origin { get; set; }
        public virtual DbSet<Pass_Ranking> Pass_Ranking { get; set; }
        public virtual DbSet<Pass_Section> Pass_Section { get; set; }
        public virtual DbSet<Passengers> Passengers { get; set; }
    
        public virtual ObjectResult<Passengers> ShowAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Passengers>("ShowAll");
        }
    
        public virtual ObjectResult<Passengers> ShowAll(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Passengers>("ShowAll", mergeOption);
        }
    }
}
