//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passengers
    {
        public int Employee_ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Section_ID { get; set; }
        public int Origin_ID { get; set; }
        public Nullable<int> Death_ID { get; set; }
        public int Rank_ID { get; set; }
        public Nullable<System.DateTime> TimeOfDeath { get; set; }
        public string condition { get; set; }
    
        public virtual Pass_DeathCause Pass_DeathCause { get; set; }
        public virtual Pass_Origin Pass_Origin { get; set; }
        public virtual Pass_Ranking Pass_Ranking { get; set; }
        public virtual Pass_Section Pass_Section { get; set; }
    }
}
