//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int Route_ID { get; set; }
        public string Departure { get; set; }
        public string Destination { get; set; }
        public System.DateTime Date { get; set; }
        public int Airplane_ID { get; set; }
    }
}
